name: Run Ansible Playbook
on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: mayank.yaml
         
